DROP TABLE TB_MEMBER;
DROP TABLE TB_GRADE;
DROP TABLE TB_AREA;

CREATE TABLE "TB_MEMBER" (
	MEMBER_ID VARCHAR2(20),
	MEMBER_PWD VARCHAR2(20),
	MEMBER_NAME VARCHAR2(30),
	GRADE number(14),
	AREA_CODE number(20)
);

SELECT * FROM TB_MEMBER;

INSERT INTO "TB_MEMBER" (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE)
VALUES ('hong01', 'pass01', '홍길동', 10, 02);

INSERT INTO "TB_MEMBER" (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE)
VALUES ('leess99', 'pass02', '이순신', 10, 032);

INSERT INTO "TB_MEMBER" (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE)
VALUES ('ss50000', 'pass03', '신사임당', 30, 031);

INSERT INTO "TB_MEMBER" (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE)
VALUES ('iu93', 'pass04', '아이유', 30, 02);

INSERT INTO "TB_MEMBER" (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE)
VALUES ('pcs1324', 'pass05', '박철수', 12, 031);

INSERT INTO "TB_MEMBER" (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE)
VALUES ('you_js', 'pass06', '유재석', 10, 02);

INSERT INTO "TB_MEMBER" (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE)
VALUES ('kyh9876', 'pass07', '김영희', 20, 031);

SELECT * FROM TB_MEMBER;



CREATE TABLE "TB_GRADE" (
	GRADE_CODE number(20),
	GRADE_NAME VARCHAR2(30)
);

SELECT * FROM TB_GRADE;

INSERT INTO "TB_GRADE" (GRADE_CODE, GRADE_NAME)
VALUES (10, '일반회원');

INSERT INTO "TB_GRADE" (GRADE_CODE, GRADE_NAME)
VALUES (20, '우수회원');

INSERT INTO "TB_GRADE" (GRADE_CODE, GRADE_NAME)
VALUES (30, '특별회원');


SELECT * FROM TB_GRADE;

CREATE TABLE "TB_AREA" (
	AREA_CODE number(20),
	AREA_NAME VARCHAR2(30)
);

INSERT INTO "TB_AREA" (AREA_CODE, AREA_NAME)
VALUES (02, '서울');

INSERT INTO "TB_AREA" (AREA_CODE, AREA_NAME)
VALUES (031, '경기');

INSERT INTO "TB_AREA" (AREA_CODE, AREA_NAME)
VALUES (032, '인천');

SELECT * FROM TB_AREA;

--  아이디에 1234가 포함되는 회원과 같은 등급, 같은지역인 회원들의 아이디, 
-- 비밀번호, 이름, 등급명, 지역명을 아이디 내림차순으로 조회
SELECT MEMBER_ID AS 아이디, MEMBER_PWD 비밀번호, MEMBER_NAME AS 이름, GRADE_NAME AS 등급명, AREA_NAME AS 지역명
FROM TB_MEMBER
JOIN TB_GRADE ON(GRADE = GRADE_CODE)
JOIN TB_AREA USING(AREA_CODE)
WHERE (GRADE, AREA_CODE) = 
    	(SELECT GRADE, AREA_CODE FROM TB_MEMBER
    	WHERE MEMBER_ID = '1234')
ORDER BY 아이디;​


-- 틀린 부분 : 
/*
 * 
JOIN TB_AREA ON (AREA_CODE = AREA_CODE)
ON을 USONG으로 바꿔야 함
같은 컬럼명을 가르키고 있기 때문에 USING으로 바꿔야 함

메인 쿼리 안에 쓴 서브쿼리에 있는
WHERE 이름이 아니라 WHERE MAMBER_NAME이 들어와야 함
해석하는 순서가 WHERE먼저 하고 SELECT 하기 때문에
DESC는 오름차순 이아니라 내림차순이여서 ASC로 바꾸거나 삭제해야 함

디비버에서 테이블을 생성할때 NUMBER를 VARCHER2로 받아서 조회가 되지 않고 오류가 났습니다.
그리고 조회를할때 컬럼명에 별칭을 붙이지 않아 적절치 않은 문법이라고 떳습니다

USING을 쓴 경우는 조회할때 컬럼 명 앞에 별칭을 따로 안 붙여도 된다.

*/



SELECT AREA_NAME 지역명, MEMBER_ID 아이디, MEMBER_NAME 이름, GRADE_NAME 등급명
FROM TB_MEMBER
JOIN TB_AREA USING (AREA_CODE)
JOIN TB_GRADE ON (GRADE = GRADE_CODE)
WHERE AREA_CODE = (
    SELECT AREA_CODE FROM TB_MEMBER
    WHERE MEMBER_NAME = '김영희')
ORDER BY 이름 ;







































DROP TABLE TB_MEMBER;
DROP TABLE TB_GRADE;
DROP TABLE TB_AREA;

CREATE TABLE "TB_MEMBER" (
	MEMBER_ID VARCHAR2(20),
	MEMBER_PWD VARCHAR2(20),
	MEMBER_NAME VARCHAR2(30),
	GRADE number(14),
	AREA_CODE number(20)
);

SELECT * FROM TB_MEMBER;

INSERT INTO "TB_MEMBER" (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE)
VALUES ('hong01', 'pass01', '홍길동', 10, 02);

INSERT INTO "TB_MEMBER" (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE)
VALUES ('leess99', 'pass02', '이순신', 10, 032);

INSERT INTO "TB_MEMBER" (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE)
VALUES ('ss50000', 'pass03', '신사임당', 30, 031);

INSERT INTO "TB_MEMBER" (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE)
VALUES ('iu93', 'pass04', '아이유', 30, 02);

INSERT INTO "TB_MEMBER" (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE)
VALUES ('pcs1324', 'pass05', '박철수', 12, 031);

INSERT INTO "TB_MEMBER" (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE)
VALUES ('you_js', 'pass06', '유재석', 10, 02);

INSERT INTO "TB_MEMBER" (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE)
VALUES ('kyh9876', 'pass07', '김영희', 20, 031);

SELECT * FROM TB_MEMBER;



CREATE TABLE "TB_GRADE" (
	GRADE_CODE number(20),
	GRADE_NAME VARCHAR2(30)
);

SELECT * FROM TB_GRADE;

INSERT INTO "TB_GRADE" (GRADE_CODE, GRADE_NAME)
VALUES (10, '일반회원');

INSERT INTO "TB_GRADE" (GRADE_CODE, GRADE_NAME)
VALUES (20, '우수회원');

INSERT INTO "TB_GRADE" (GRADE_CODE, GRADE_NAME)
VALUES (30, '특별회원');


SELECT * FROM TB_GRADE;

CREATE TABLE "TB_AREA" (
	AREA_CODE number(20),
	AREA_NAME VARCHAR2(30)
);

INSERT INTO "TB_AREA" (AREA_CODE, AREA_NAME)
VALUES (02, '서울');

INSERT INTO "TB_AREA" (AREA_CODE, AREA_NAME)
VALUES (031, '경기');

INSERT INTO "TB_AREA" (AREA_CODE, AREA_NAME)
VALUES (032, '인천');

SELECT * FROM TB_AREA;

SELECT MEMBER_ID 아이디, MEMBER_PWD 비밀번호, MEMBER_NAME 이름, GRADE_NAME 등급명
FROM TB_MEMBER
JOIN TB_AREA USING(AREA_CODE)
JOIN TB_GRADE ON(GRADE = GRADE_CODE)
WHERE (GRADE, AREA_CODE) = (SELECT GRADE, AREA_CODE 
														FROM TB_MEMBER
   													WHERE MEMBER_ID = '%1234%')
														ORDER BY 아이디;​





























CREATE TABLE "TB_MEMBER" (
	MEMBER_ID VARCHAR2(20),
	MEMBER_PWD VARCHAR2(20),
	MEMBER_NAME VARCHAR2(30),
	GRADE VARCHAR2(14),
	AREA_CODE VARCHAR2(20)
);

SELECT * FROM TB_MEMBER;

INSERT INTO "TB_MEMBER" (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE)
VALUES ('hong01', 'pass01', '홍길동', 10, 02);

INSERT INTO "TB_MEMBER" (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE)
VALUES ('leess99', 'pass02', '이순신', 10, 032);

INSERT INTO "TB_MEMBER" (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE)
VALUES ('ss50000', 'pass03', '신사임당', 30, 031);

INSERT INTO "TB_MEMBER" (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE)
VALUES ('iu93', 'pass04', '아이유', 30, 02);

INSERT INTO "TB_MEMBER" (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE)
VALUES ('pcs1324', 'pass05', '박철수', 12, 031);

INSERT INTO "TB_MEMBER" (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE)
VALUES ('you_js', 'pass06', '유재석', 10, 02);

INSERT INTO "TB_MEMBER" (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE)
VALUES ('kyh9876', 'pass07', '김영희', 20, 031);

SELECT * FROM TB_MEMBER;



CREATE TABLE "TB_GRADE" (
	GRADE_CODE VARCHAR2(20),
	GRADE_NAME VARCHAR2(30)
);

SELECT * FROM TB_GRADE;

INSERT INTO "TB_GRADE" (GRADE_CODE, GRADE_NAME)
VALUES (10, '일반회원');

INSERT INTO "TB_GRADE" (GRADE_CODE, GRADE_NAME)
VALUES (20, '우수회원');

INSERT INTO "TB_GRADE" (GRADE_CODE, GRADE_NAME)
VALUES (30, '특별회원');


SELECT * FROM TB_GRADE;




CREATE TABLE "TB_AREA" (
	AREA_CODE VARCHAR2(20),
	AREA_NAME VARCHAR2(30)
);

INSERT INTO TB_AREA (AREA_CODE, AREA_NAME)
VALUES ('02', '서울');

INSERT INTO TB_AREA (AREA_CODE, AREA_NAME)
VALUES ('031', '경기');

INSERT INTO TB_AREA (AREA_CODE, AREA_NAME)
VALUES ('032', '인천');

SELECT * FROM TB_AREA;


SELECT AREA_NAME 지역명, MEMBER_ID 아이디, MEMBER_NAME 이름, GRADE_NAME 등급명
FROM TB_MEMBER
JOIN TB_GRADE ON(GRADE = GRADE_CODE)
JOIN TB_AREA ON (AREA_CODE = AREA_CODE)
WHERE AREA_CODE = (
    SELECT AREA_CODE FROM TB_MEMBER
    WHERE 이름 = '김영희')
ORDER BY 이름 DESC;
