--내가 작성
DROP TABLE TB_MEMBER;
DROP TABLE TB_GRADE;
DROP TABLE TB_AREA;

CREATE TABLE "TB_MEMBER" (
	MEMBER_ID VARCHAR2(20),
	MEMBER_PWD VARCHAR2(20),
	MEMBER_NAME VARCHAR2(30),
	GRADE number(14),
	AREA_CODE number(20)
);

SELECT * FROM TB_MEMBER;

INSERT INTO "TB_MEMBER" (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE)
VALUES ('hong01', 'pass01', '홍길동', 10, 02);

INSERT INTO "TB_MEMBER" (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE)
VALUES ('leess99', 'pass02', '이순신', 10, 032);

INSERT INTO "TB_MEMBER" (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE)
VALUES ('ss50000', 'pass03', '신사임당', 30, 031);

INSERT INTO "TB_MEMBER" (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE)
VALUES ('iu93', 'pass04', '아이유', 30, 02);

INSERT INTO "TB_MEMBER" (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE)
VALUES ('pcs1324', 'pass05', '박철수', 12, 031);

INSERT INTO "TB_MEMBER" (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE)
VALUES ('you_js', 'pass06', '유재석', 10, 02);

INSERT INTO "TB_MEMBER" (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE)
VALUES ('kyh9876', 'pass07', '김영희', 20, 031);

SELECT * FROM TB_MEMBER;



CREATE TABLE "TB_GRADE" (
	GRADE_CODE number(20),
	GRADE_NAME VARCHAR2(30)
);

SELECT * FROM TB_GRADE;

INSERT INTO "TB_GRADE" (GRADE_CODE, GRADE_NAME)
VALUES (10, '일반회원');

INSERT INTO "TB_GRADE" (GRADE_CODE, GRADE_NAME)
VALUES (20, '우수회원');

INSERT INTO "TB_GRADE" (GRADE_CODE, GRADE_NAME)
VALUES (30, '특별회원');


SELECT * FROM TB_GRADE;




CREATE TABLE "TB_AREA" (
	AREA_CODE VARCHAR2(20),
	AREA_NAME VARCHAR2(30)
);

INSERT INTO TB_AREA (AREA_CODE, AREA_NAME)
VALUES ('02', '서울');

INSERT INTO TB_AREA (AREA_CODE, AREA_NAME)
VALUES ('031', '경기');

INSERT INTO TB_AREA (AREA_CODE, AREA_NAME)
VALUES ('032', '인천');

SELECT * FROM TB_AREA;

[작성한 SQL]
SELECT A.AREA_NAME 지역명, M.MEMBER_ID 아이디,M.MEMBER_NAME 이름, G.GRADE_NAME 등급명
FROM TB_MEMBER M
JOIN TB_AREA A USING (AREA_CODE)
JOIN TB_GRADE G ON (G.GRADE_CODE = M.GRADE)
WHERE M.MEMBER_NAME = (SELECT AREA_CODE FROM TB_MEMBER WHERE MEMBER_NAME ='김영희')
ORDER BY 이름;​

--------- 고친 코드

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;--이전구문 허용

CREATE USER TB_MEMBER IDENTIFIED BY 1234;-- 생성
CREATE USER TB_GRADE IDENTIFIED BY 1234;-- 생성
CREATE USER TB_AREA IDENTIFIED BY 1234;-- 생성

GRANT CREATE SESSION TO TB_MEMBER;--권한부여
GRANT CREATE SESSION TO TB_GRADE;--권한부여
GRANT CREATE SESSION TO TB_AREA;--권한부여

GRANT CREATE TABLE TO TB_MEMBER;-- 테이블 만들 권한
GRANT CREATE TABLE TO TB_GRADE;
GRANT CREATE TABLE TO TB_AREA;
DROP TABLE TB_MEMBER;
DROP TABLE TB_GRADE;
DROP TABLE TB_AREA;


CREATE TABLE "TB_MEMBER" (
	MEMBER_ID VARCHAR2(20),
	MEMBER_PWD VARCHAR2(20),
	MEMBER_NAME VARCHAR2(30),
	GRADE number(14),
	AREA_CODE number(20)
);

SELECT * FROM TB_MEMBER;

INSERT INTO "TB_MEMBER" (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE)
VALUES ('hong01', 'pass01', '홍길동', 10, 02);

INSERT INTO "TB_MEMBER" (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE)
VALUES ('leess99', 'pass02', '이순신', 10, 032);

INSERT INTO "TB_MEMBER" (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE)
VALUES ('ss50000', 'pass03', '신사임당', 30, 031);

INSERT INTO "TB_MEMBER" (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE)
VALUES ('iu93', 'pass04', '아이유', 30, 02);

INSERT INTO "TB_MEMBER" (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE)
VALUES ('pcs1324', 'pass05', '박철수', 12, 031);

INSERT INTO "TB_MEMBER" (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE)
VALUES ('you_js', 'pass06', '유재석', 10, 02);

INSERT INTO "TB_MEMBER" (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE)
VALUES ('kyh9876', 'pass07', '김영희', 20, 031);





CREATE TABLE "TB_GRADE" (
	GRADE_CODE number(20),
	GRADE_NAME VARCHAR2(30)
);

SELECT * FROM TB_GRADE;

INSERT INTO "TB_GRADE" (GRADE_CODE, GRADE_NAME)
VALUES (10, '일반회원');

INSERT INTO "TB_GRADE" (GRADE_CODE, GRADE_NAME)
VALUES (20, '우수회원');

INSERT INTO "TB_GRADE" (GRADE_CODE, GRADE_NAME)
VALUES (30, '특별회원');


SELECT * FROM TB_GRADE;




CREATE TABLE "TB_AREA" (
	AREA_CODE number(20),
	AREA_NAME VARCHAR2(30)
);

INSERT INTO "TB_AREA" (AREA_CODE, AREA_NAME)
VALUES (02, '서울');

INSERT INTO "TB_AREA" (AREA_CODE, AREA_NAME)
VALUES (031, '경기');

INSERT INTO "TB_AREA" (AREA_CODE, AREA_NAME)
VALUES (032, '인천');

SELECT * FROM TB_AREA;

SELECT A.AREA_NAME 지역명, M.MEMBER_ID 아이디, M.MEMBER_NAME 이름, G.GRADE_NAME 등급명
FROM TB_MEMBER M
JOIN TB_AREA A ON (A.AREA_CODE = M.AREA_CODE)
JOIN TB_GRADE G ON(M.GRADE = G.GRADE_CODE)
WHERE A.AREA_CODE = (
    SELECT AREA_CODE FROM TB_MEMBER
    WHERE MEMBER_NAME = '김영희')
ORDER BY 이름 ;


SELECT A.AREA_NAME 지역명, M.MEMBER_ID 아이디,M.MEMBER_NAME 이름, G.GRADE_NAME 등급명
FROM TB_MEMBER M
JOIN TB_AREA A USING (AREA_CODE)
JOIN TB_GRADE G ON (G.GRADE_CODE = M.GRADE)
WHERE M.MEMBER_NAME = (SELECT AREA_CODE FROM TB_MEMBER WHERE MEMBER_NAME ='김영희')
ORDER BY 이름;



-- TB_MEMBER 테이블 생성
CREATE TABLE TB_MEMBER (
    MEMBER_ID VARCHAR2(20) PRIMARY KEY,
    MEMBER_PWD VARCHAR2(20) NOT NULL,
    MEMBER_NAME VARCHAR2(30) NOT NULL,
    GRADE VARCHAR2(10) NOT NULL,
    AREA_CODE VARCHAR2(10) NOT NULL
);

-- TB_MEMBER 데이터 삽입
INSERT INTO TB_MEMBER (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE) VALUES ('hong01', 'pass01', '홍길동', '10', '02');
INSERT INTO TB_MEMBER (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE) VALUES ('leess99', 'pass02', '이순신', '10', '032');
INSERT INTO TB_MEMBER (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE) VALUES ('ss50000', 'pass03', '신사임당', '30', '031');
INSERT INTO TB_MEMBER (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE) VALUES ('iu93', 'pass04', '아이유', '30', '02');
INSERT INTO TB_MEMBER (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE) VALUES ('pcs1324', 'pass05', '박철수', '12', '031');
INSERT INTO TB_MEMBER (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE) VALUES ('you_js', 'pass06', '유재석', '10', '02');
INSERT INTO TB_MEMBER (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GRADE, AREA_CODE) VALUES ('kyh9876', 'pass07', '김영희', '20', '031');

SELECT * FROM TB_MEMBER;

-- TB_GRADE 테이블 생성
CREATE TABLE TB_GRADE (
    GRADE_CODE VARCHAR2(10) PRIMARY KEY,
    GRADE_NAME VARCHAR2(30) NOT NULL
);

-- TB_GRADE 데이터 삽입
INSERT INTO TB_GRADE (GRADE_CODE, GRADE_NAME) VALUES ('10', '일반회원');
INSERT INTO TB_GRADE (GRADE_CODE, GRADE_NAME) VALUES ('20', '우수회원');
INSERT INTO TB_GRADE (GRADE_CODE, GRADE_NAME) VALUES ('30', '특별회원');

SELECT * FROM TB_GRADE;

-- TB_AREA 테이블 생성
CREATE TABLE TB_AREA (
    AREA_CODE VARCHAR2(10) PRIMARY KEY,
    AREA_NAME VARCHAR2(30) NOT NULL
);

-- TB_AREA 데이터 삽입
INSERT INTO TB_AREA (AREA_CODE, AREA_NAME) VALUES ('02', '서울');
INSERT INTO TB_AREA (AREA_CODE, AREA_NAME) VALUES ('031', '경기');
INSERT INTO TB_AREA (AREA_CODE, AREA_NAME) VALUES ('032', '인천');

SELECT * FROM TB_AREA;


SELECT A.AREA_NAME 지역명, M.MEMBER_ID 아이디, M.MEMBER_NAME 이름, G.GRADE_NAME 등급명
FROM TB_MEMBER M
JOIN TB_AREA A ON (A.AREA_CODE  = M.AREA_CODE)
JOIN TB_GRADE G ON(M.GRADE = G.GRADE_CODE)
WHERE A.AREA_CODE = (
    SELECT AREA_CODE FROM TB_MEMBER
    WHERE MEMBER_NAME = '김영희')
ORDER BY 이름;